name: push notification (main)
on:
  push:
    branches:
      - main
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 465              # Puerto SSL
          username: ${{ secrets.MAIL }}
          password: ${{ secrets.PASS }}
          subject: "shalom"
          to: rodrigo.penam@iteso.mx, haziel.murillo@iteso.mx, victor.ortega@iteso.mx
          from: ${{ secrets.MAIL }}
          body: commit en main nih
